module register64(clk,reset,writeEnable,valIn,valOut);
    input clk,reset,writeEnable;
    input [63:0] valIn;
    output [63:0] valOut;

    wire cEn;
    and cEnAnd(cEn,writeEnable,clk);

    dffe_ref d0(valOut[0], valIn[0], clk, writeEnable, 1'b0);
    dffe_ref d1(valOut[1], valIn[1], clk, writeEnable, 1'b0);
    dffe_ref d2(valOut[2], valIn[2], clk, writeEnable, 1'b0);
    dffe_ref d3(valOut[3], valIn[3], clk, writeEnable, 1'b0);
    dffe_ref d4(valOut[4], valIn[4], clk, writeEnable, 1'b0);
    dffe_ref d5(valOut[5], valIn[5], clk, writeEnable, 1'b0);
    dffe_ref d6(valOut[6], valIn[6], clk, writeEnable, 1'b0);
    dffe_ref d7(valOut[7], valIn[7], clk, writeEnable, 1'b0);
    dffe_ref d8(valOut[8], valIn[8], clk, writeEnable, 1'b0);
    dffe_ref d9(valOut[9], valIn[9], clk, writeEnable, 1'b0);
    dffe_ref d10(valOut[10], valIn[10], clk, writeEnable, 1'b0);
    dffe_ref d11(valOut[11], valIn[11], clk, writeEnable, 1'b0);
    dffe_ref d12(valOut[12], valIn[12], clk, writeEnable, 1'b0);
    dffe_ref d13(valOut[13], valIn[13], clk, writeEnable, 1'b0);
    dffe_ref d14(valOut[14], valIn[14], clk, writeEnable, 1'b0);
    dffe_ref d15(valOut[15], valIn[15], clk, writeEnable, 1'b0);
    dffe_ref d16(valOut[16], valIn[16], clk, writeEnable, 1'b0);
    dffe_ref d17(valOut[17], valIn[17], clk, writeEnable, 1'b0);
    dffe_ref d18(valOut[18], valIn[18], clk, writeEnable, 1'b0);
    dffe_ref d19(valOut[19], valIn[19], clk, writeEnable, 1'b0);
    dffe_ref d20(valOut[20], valIn[20], clk, writeEnable, 1'b0);
    dffe_ref d21(valOut[21], valIn[21], clk, writeEnable, 1'b0);
    dffe_ref d22(valOut[22], valIn[22], clk, writeEnable, 1'b0);
    dffe_ref d23(valOut[23], valIn[23], clk, writeEnable, 1'b0);
    dffe_ref d24(valOut[24], valIn[24], clk, writeEnable, 1'b0);
    dffe_ref d25(valOut[25], valIn[25], clk, writeEnable, 1'b0);
    dffe_ref d26(valOut[26], valIn[26], clk, writeEnable, 1'b0);
    dffe_ref d27(valOut[27], valIn[27], clk, writeEnable, 1'b0);
    dffe_ref d28(valOut[28], valIn[28], clk, writeEnable, 1'b0);
    dffe_ref d29(valOut[29], valIn[29], clk, writeEnable, 1'b0);
    dffe_ref d30(valOut[30], valIn[30], clk, writeEnable, 1'b0);
    dffe_ref d31(valOut[31], valIn[31], clk, writeEnable, 1'b0);
    dffe_ref d32(valOut[32], valIn[32], clk, writeEnable, reset);
    dffe_ref d33(valOut[33], valIn[33], clk, writeEnable, reset);
    dffe_ref d34(valOut[34], valIn[34], clk, writeEnable, reset);
    dffe_ref d35(valOut[35], valIn[35], clk, writeEnable, reset);
    dffe_ref d36(valOut[36], valIn[36], clk, writeEnable, reset);
    dffe_ref d37(valOut[37], valIn[37], clk, writeEnable, reset);
    dffe_ref d38(valOut[38], valIn[38], clk, writeEnable, reset);
    dffe_ref d39(valOut[39], valIn[39], clk, writeEnable, reset);
    dffe_ref d40(valOut[40], valIn[40], clk, writeEnable, reset);
    dffe_ref d41(valOut[41], valIn[41], clk, writeEnable, reset);
    dffe_ref d42(valOut[42], valIn[42], clk, writeEnable, reset);
    dffe_ref d43(valOut[43], valIn[43], clk, writeEnable, reset);
    dffe_ref d44(valOut[44], valIn[44], clk, writeEnable, reset);
    dffe_ref d45(valOut[45], valIn[45], clk, writeEnable, reset);
    dffe_ref d46(valOut[46], valIn[46], clk, writeEnable, reset);
    dffe_ref d47(valOut[47], valIn[47], clk, writeEnable, reset);
    dffe_ref d48(valOut[48], valIn[48], clk, writeEnable, reset);
    dffe_ref d49(valOut[49], valIn[49], clk, writeEnable, reset);
    dffe_ref d50(valOut[50], valIn[50], clk, writeEnable, reset);
    dffe_ref d51(valOut[51], valIn[51], clk, writeEnable, reset);
    dffe_ref d52(valOut[52], valIn[52], clk, writeEnable, reset);
    dffe_ref d53(valOut[53], valIn[53], clk, writeEnable, reset);
    dffe_ref d54(valOut[54], valIn[54], clk, writeEnable, reset);
    dffe_ref d55(valOut[55], valIn[55], clk, writeEnable, reset);
    dffe_ref d56(valOut[56], valIn[56], clk, writeEnable, reset);
    dffe_ref d57(valOut[57], valIn[57], clk, writeEnable, reset);
    dffe_ref d58(valOut[58], valIn[58], clk, writeEnable, reset);
    dffe_ref d59(valOut[59], valIn[59], clk, writeEnable, reset);
    dffe_ref d60(valOut[60], valIn[60], clk, writeEnable, reset);
    dffe_ref d61(valOut[61], valIn[61], clk, writeEnable, reset);
    dffe_ref d62(valOut[62], valIn[62], clk, writeEnable, reset);
    dffe_ref d63(valOut[63], valIn[63], clk, writeEnable, reset);

endmodule