# Clock on E3
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {clk}];

# Rest Signal
set_property PACKAGE_PIN C12 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

# VGA Port
set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

# Sync Ports
set_property PACKAGE_PIN B11 [get_ports hSync]
set_property PACKAGE_PIN B12 [get_ports vSync]
set_property IOSTANDARD LVCMOS33 [get_ports hSync]
set_property IOSTANDARD LVCMOS33 [get_ports vSync]

#Buttons
set_property -dict { PACKAGE_PIN N17   IOSTANDARD LVCMOS33 } [get_ports { BTNC }]; #IO_L9P_T1_DQS_14 Sch=btnc
set_property -dict { PACKAGE_PIN M18   IOSTANDARD LVCMOS33 } [get_ports { BTNU }]; #IO_L4N_T0_D05_14 Sch=btnu
set_property -dict { PACKAGE_PIN P17   IOSTANDARD LVCMOS33 } [get_ports { BTNL }]; #IO_L12P_T1_MRCC_14 Sch=btnl
set_property -dict { PACKAGE_PIN M17   IOSTANDARD LVCMOS33 } [get_ports { BTNR }]; #IO_L10N_T1_D15_14 Sch=btnr
set_property -dict { PACKAGE_PIN P18   IOSTANDARD LVCMOS33 } [get_ports { BTND }]; #IO_L9N_T1_DQS_D13_14 Sch=btnd

#LED Testing
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { LED[0] }]; #IO_L18P_T2_A24_15 Sch=led[0]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { LED[1] }]; #IO_L24P_T3_RS1_15 Sch=led[1]
set_property -dict { PACKAGE_PIN J13   IOSTANDARD LVCMOS33 } [get_ports { LED[2] }]; #IO_L17N_T2_A25_15 Sch=led[2]
set_property -dict { PACKAGE_PIN N14   IOSTANDARD LVCMOS33 } [get_ports { LED[3] }]; #IO_L8P_T1_D11_14 Sch=led[3]
set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { LED[4] }]; #IO_L7P_T1_D09_14 Sch=led[4]
set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports { LED[5] }]; #IO_L18N_T2_A11_D27_14 Sch=led[5]
set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { LED[6] }]; #IO_L17P_T2_A14_D30_14 Sch=led[6]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { LED[7] }]; #IO_L18P_T2_A12_D28_14 Sch=led[7]
set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { LED[8] }]; #IO_L16N_T2_A15_D31_14 Sch=led[8]
set_property -dict { PACKAGE_PIN T15   IOSTANDARD LVCMOS33 } [get_ports { LED[9] }]; #IO_L14N_T2_SRCC_14 Sch=led[9]
set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports { LED[10] }]; #IO_L22P_T3_A05_D21_14 Sch=led[10]
set_property -dict { PACKAGE_PIN T16   IOSTANDARD LVCMOS33 } [get_ports { LED[11] }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=led[11]
set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports { LED[12] }]; #IO_L16P_T2_CSI_B_14 Sch=led[12]
set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports { LED[13] }]; #IO_L22N_T3_A04_D20_14 Sch=led[13]
set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { LED[14] }]; #IO_L20N_T3_A07_D23_14 Sch=led[14]
set_property -dict { PACKAGE_PIN V11   IOSTANDARD LVCMOS33 } [get_ports { LED[15] }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]

set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_0/comp_2_1/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_0/comp_2_2/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_0/comp_2_3/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_1/comp_2_0/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_1/comp_2_1/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_1/comp_2_2/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_1/comp_2_3/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_2/comp_2_0/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_2/comp_2_1/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_2/comp_2_2/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_2/comp_2_3/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_3/comp_2_0/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_3/comp_2_1/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_3/comp_2_2/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/compExcept/comp_2_3/comp_2_3/gt_mux/w1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[0]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[11]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[13]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[15]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[17]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[19]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[1]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[21]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[23]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[25]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[27]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[29]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[31]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[3]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[5]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/dividee/plusV/wy[7]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/multiplyy/compAGT1/comp_2_0/comp_2_0/gt_from_mux]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/multiplyy/compBGT1/comp_2_0/comp_2_0/gt_from_mux]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets multtt/multiplyy/compBMax/comp_2_0/GT10]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_104_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_105_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_106_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_107_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_111_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_112_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_113_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_120_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_121_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_122_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_123__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_124__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_128_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_129_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_130_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_132_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_133_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_135_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_136_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_137_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_138_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_139_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_146_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_147_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_149_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_150_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_151_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_152_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_153_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_154_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_155_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_156_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_157_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_158_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_159_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_160_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_161_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_162_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_163_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_164_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_165_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_166_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_167_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_168_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_169_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_170_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_171_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_172_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_173_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_174_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_175_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_176_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_24__6_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_27__3_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_55__1_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_6__58_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_76__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_77__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_92__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_93__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_94__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_76_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_77_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_93_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_94_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_123_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_124_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_128__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_130__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_132__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_136__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_138__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_24__4_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_28__3_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_55__0_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_6__50_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_24__3_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_28__4_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_6__79_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_92_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_24__2_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_20__6_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_55_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_6__42_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_24__5_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_27__1_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_6__72_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_6__49_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_4__54_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_6__48_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_4__59_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_6__64_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_4__53_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_55__2_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_5__50_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_29__2_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_22__2_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets q_i_6__46_n_0]








#macros pacman test
create_macro m1
update_macro m1 {PacmanImageData/MemoryArray_reg_0_127_0_0/LOW/WADR6 X1Y2 PacmanImageData/MemoryArray_reg_0_127_0_0/HIGH/WADR7 X1Y3}
#WADR6
#create_pblock {pblock_test1]}
#resize_pblock {pblock_test1} -add CLOCKREGION_X1Y2:CLOCKREGION_X1Y2
#add_cells_to_pblock {pblock_test} [get_cells -hier -filter {NAME =~ PacmanImageData/MemoryArray_reg_0_127_0_0/LOW}] -clear_locs

#create_pblock {pblock_test2]}
#resize_pblock {pblock_test2} -add CLOCKREGION_X1Y3:CLOCKREGION_X1Y3
#add_cells_to_pblock {pblock_test} [get_cells -hier -filter {NAME =~ PacmanImageData/MemoryArray_reg_0_127_0_0/HIGH}] -clear_locs
